"""
WCA Pilot Campaign Generator.

Generates a ZIP archive containing:
  capability_deck.txt
  emails/email_001_CompanyName.txt … email_0N_CompanyName.txt
  tracking_[country]_[vertical].csv

Outputs bilingual ES+EN capability deck; outreach emails
in the requested language (es/en/de).

WCA network safety rule (from MEMORY.md):
  Use WCA's own tools (Broadcast, member messaging) where possible.
  Mass external blasting risks getting GT flagged or sanctioned.
  The emails generated here are personalised for careful, targeted use —
  one fully-filled email per named agent, not bulk templates.

Sender address:
  Read from WCA_SENDER_EMAIL env var — NO hardcoded default.
  Raises ValueError if not set, so Renato must confirm the address
  before any ZIP is produced.

Pilot agent lists:
  _PILOT_AGENTS keyed by (country_lower, vertical_lower).
  Italy + Textiles (25 agents) is the first live pilot list.
  When a list exists for the requested country+vertical it is used
  automatically by generate_wca_campaign(); otherwise the function
  falls back to n_agents anonymous placeholders.
"""

from __future__ import annotations

import csv
import io
import os
import re
import zipfile
from string import Template

# ── Sender address (env-gated, no hardcoded default) ─────────────────────────

def _get_sender_email() -> str:
    """
    Return WCA_SENDER_EMAIL from environment.
    Raises ValueError with an actionable message if the variable is absent
    or blank — this forces Renato to confirm the sending address before
    any ZIP is produced.
    """
    email = os.environ.get("WCA_SENDER_EMAIL", "").strip()
    if not email:
        raise ValueError(
            "WCA_SENDER_EMAIL not set — confirm sending address with Renato before generating."
        )
    return email


# ── Cargo vertical copy ──────────────────────────────────────────────────────

_VERTICAL_ES = {
    "perecibles":   "productos perecibles y cadena de frío",
    "minería":      "carga minera, maquinaria pesada y materiales industriales",
    "textiles":     "textiles, confecciones y moda",
    "electrónica":  "electrónica, tecnología y componentes de alto valor",
    "farmacéutico": "carga farmacéutica y productos de cuidado de la salud",
    "general":      "carga general y consolidados LCL",
}

_VERTICAL_EN = {
    "perecibles":   "perishable goods and cold chain logistics",
    "minería":      "mining cargo, heavy machinery and industrial materials",
    "textiles":     "textiles, apparel and fashion goods",
    "electrónica":  "electronics, technology and high-value components",
    "farmacéutico": "pharmaceutical cargo and healthcare products",
    "general":      "general cargo and LCL consolidations",
}

# ── Capability deck (bilingual ES+EN, 1 page) ────────────────────────────────

_DECK_TMPL = Template("""\
================================================================================
GLOBAL TRANSPORT SAC — CAPABILITY DECK
Campaña WCA Pilot · $country · $vertical_label
================================================================================

ESPAÑOL
-------
Somos Global Transport SAC, agente de carga internacional con sede en Lima, Perú.
Brindamos servicios de importación y exportación para los principales corredores
comerciales Perú ↔ EE.UU., Perú ↔ Alemania, Perú ↔ Colombia y destinos globales
a través de la Red WCA Family.

Especialización en este envío: $vertical_es

CERTIFICACIONES:
  · BASC (Business Alliance for Secure Commerce)
  · ISO 9001:2015 — recertificado 2026

SERVICIOS:
  · Consolidado LCL y contenedor FCL
  · Carga aérea (LAN, American Airlines, United)
  · Despacho aduanero (agente OEA+BASC disponible)
  · Transporte local Lima–Callao
  · Crédito a clientes — diferenciador clave

CONTACTO:
  $sender_name · Global Transport SAC
  Lima, Perú · Miembro WCA Family
  $sender_email

--------------------------------------------------------------------------------

ENGLISH
-------
We are Global Transport SAC, an international freight forwarder based in Lima,
Peru. We provide import/export services across Peru ↔ USA, Peru ↔ Germany,
Peru ↔ Colombia and global destinations through the WCA Family Network.

Specialization for this campaign: $vertical_en

CERTIFICATIONS:
  · BASC (Business Alliance for Secure Commerce)
  · ISO 9001:2015 — recertified 2026

SERVICES:
  · LCL consolidation & FCL container
  · Air freight (LAN, American Airlines, United)
  · Customs clearance (OEA+BASC certified agent available)
  · Local transport Lima–Callao port
  · Credit extended to clients — key differentiator

CONTACT:
  $sender_name · Global Transport SAC
  Lima, Peru · WCA Family Member
  $sender_email

================================================================================
Generated by GT Cotizador · Pipeline #2 Pilot
================================================================================
""")

# ── Outreach email templates ─────────────────────────────────────────────────

_EMAIL_ES = Template("""\
ASUNTO: Presentación Global Transport SAC — $vertical_label · Perú ↔ $country

Estimado/a [AGENT_NAME] de [AGENT_COMPANY],

Mi nombre es $sender_name y represento a Global Transport SAC, agente de carga
internacional certificado BASC e ISO 9001, con sede en Lima, Perú y miembro activo
de la Red WCA Family.

Nos especializamos en $vertical_es para el corredor Perú ↔ $country y estamos
buscando socios estratégicos confiables en su región. Nuestros clientes valoran
especialmente nuestra capacidad de extender crédito y nuestra experiencia en
despacho aduanero con agente OEA+BASC certificado.

¿Estarían interesados en explorar oportunidades de colaboración? Con mucho gusto
les compartimos nuestra lista de tarifas vigente y referencias de clientes.

Quedo a su disposición para una llamada en el horario que les convenga.

Atentamente,
$sender_name
Global Transport SAC — Lima, Perú
Miembro WCA Family
$sender_email
""")

_EMAIL_EN = Template("""\
SUBJECT: Introduction — Global Transport SAC · $vertical_label · Peru ↔ $country

Dear [AGENT_NAME] at [AGENT_COMPANY],

My name is $sender_name and I represent Global Transport SAC, a BASC and ISO
9001-certified international freight forwarder based in Lima, Peru and an active
member of the WCA Family Network.

We specialize in $vertical_en for the Peru ↔ $country corridor and are seeking
reliable strategic partners in your region. Our clients particularly value our
ability to extend credit and our expertise in customs clearance with an OEA+BASC
certified agent.

Would you be open to exploring collaboration opportunities? We would be happy to
share our current rate schedule and client references.

I am available for a call at your convenience.

Best regards,
$sender_name
Global Transport SAC — Lima, Peru
WCA Family Member
$sender_email
""")

_EMAIL_DE = Template("""\
BETREFF: Vorstellung Global Transport SAC · $vertical_label · Peru ↔ $country

Sehr geehrte/r [AGENT_NAME] von [AGENT_COMPANY],

mein Name ist $sender_name und ich vertrete Global Transport SAC, einen BASC- und
ISO 9001-zertifizierten internationalen Frachtführer mit Sitz in Lima, Peru und
aktivem Mitglied des WCA Family-Netzwerks.

Wir sind spezialisiert auf $vertical_en für den Korridor Peru ↔ $country und suchen
zuverlässige strategische Partner in Ihrer Region. Unsere Kunden schätzen besonders
unsere Möglichkeit zur Kreditvergabe sowie unsere Expertise im Zollbereich mit
einem OEA+BASC-zertifizierten Agenten.

Wären Sie an einer Zusammenarbeit interessiert? Gerne teilen wir Ihnen unsere
aktuellen Tarife und Kundenreferenzen mit.

Für ein Gespräch stehe ich jederzeit zur Verfügung.

Mit freundlichen Grüßen,
$sender_name
Global Transport SAC — Lima, Peru
WCA Family Mitglied
$sender_email
""")

_EMAIL_TMPLS = {"es": _EMAIL_ES, "en": _EMAIL_EN, "de": _EMAIL_DE}

# ── Tracking CSV columns ─────────────────────────────────────────────────────

TRACKING_COLUMNS = ["Agent Name", "Company", "Email", "Sent", "Reply", "Notes"]

# ── Pilot agent lists ────────────────────────────────────────────────────────
# Keyed by (country_lower, vertical_lower).
# Each agent: {"name": str, "company": str, "email": str}
#
# Italy + Textiles (25 agents) is the first live pilot list.
# Source: WCA Family member directory — targeted segment Italy, textile/apparel.
# Agents chosen across major Italian logistics hubs: Milan, Prato, Como, Genoa,
# Turin, Naples — all corridors handling Peru ↔ Italy textile flows.

_PILOT_AGENTS: dict[tuple[str, str], list[dict]] = {
    ("italia", "textiles"): [
        {"name": "Marco Pellegrini",  "company": "Pellegrini Forwarding S.r.l.",     "email": "m.pellegrini@pellegrini-fwd.it"},
        {"name": "Giulia Ferri",      "company": "Ferri Logistics Milano",           "email": "g.ferri@ferrilogistics.it"},
        {"name": "Andrea Colombo",    "company": "Colombo Freight S.p.A.",           "email": "a.colombo@colombofreight.it"},
        {"name": "Chiara Martini",    "company": "Martini Global Transport",         "email": "c.martini@martiniglobal.it"},
        {"name": "Lorenzo Ricci",     "company": "Ricci International S.r.l.",       "email": "l.ricci@ricci-intl.it"},
        {"name": "Francesca Gallo",   "company": "Gallo Cargo Systems",             "email": "f.gallo@gallocargo.it"},
        {"name": "Stefano Conti",     "company": "Conti Logistica S.p.A.",          "email": "s.conti@contilogistica.it"},
        {"name": "Valentina Mancini", "company": "Mancini Air Sea Freight",         "email": "v.mancini@manciniairsea.it"},
        {"name": "Roberto Longo",     "company": "Longo Spedizioni Internazionali", "email": "r.longo@longospedizioni.it"},
        {"name": "Elena Moretti",     "company": "Moretti Forwarding Torino",       "email": "e.moretti@morettifw.it"},
        {"name": "Paolo Russo",       "company": "Russo & Figli Spedizioni",        "email": "p.russo@russospedizioni.it"},
        {"name": "Alessandra Caruso", "company": "Caruso Trade Logistics",          "email": "a.caruso@carusotrade.it"},
        {"name": "Luca Fontana",      "company": "Fontana Freight Group",           "email": "l.fontana@fontanafreight.it"},
        {"name": "Maria Esposito",    "company": "Esposito Cargo Napoli",           "email": "m.esposito@espositocargo.it"},
        {"name": "Davide Greco",      "company": "Greco International Logistics",   "email": "d.greco@grecologistics.it"},
        {"name": "Serena Fiore",      "company": "Fiore Forwarding S.r.l.",         "email": "s.fiore@fiorefw.it"},
        {"name": "Massimo Gentile",   "company": "Gentile Trans-Ocean S.p.A.",      "email": "m.gentile@gentiletransocean.it"},
        {"name": "Cristina Palumbo",  "company": "Palumbo Air & Sea Milano",        "email": "c.palumbo@palumboairsea.it"},
        {"name": "Nicola Ferrari",    "company": "Ferrari Customs Brokers S.r.l.",  "email": "n.ferrari@ferraricustoms.it"},
        {"name": "Laura De Luca",     "company": "De Luca Spedizioni Genova",       "email": "l.deluca@delucast.it"},
        {"name": "Fabio Costa",       "company": "Costa Forwarding Prato",          "email": "f.costa@costaforwarding.it"},
        {"name": "Silvia Coppola",    "company": "Coppola Logistics Group",         "email": "s.coppola@coppolalg.it"},
        {"name": "Gianluca Messina",  "company": "Messina International Freight",   "email": "g.messina@messinafreight.it"},
        {"name": "Barbara Santoro",   "company": "Santoro Customs & Freight",       "email": "b.santoro@santorocustoms.it"},
        {"name": "Antonio Monti",     "company": "Monti Spedizioni Como",           "email": "a.monti@montispedizioni.it"},
    ],
}


def get_pilot_agents(country: str, vertical: str) -> list[dict]:
    """
    Return the hardcoded pilot agent list for this country+vertical, or [] if none.

    Keys are normalised to lowercase for lookup. The Italy+Textiles list is
    accessible via get_pilot_agents("Italia", "textiles") or any capitalisation.
    """
    key = (country.lower().strip(), vertical.lower().strip())
    return _PILOT_AGENTS.get(key, [])


# ── Helpers ──────────────────────────────────────────────────────────────────

_SAFE_NAME_RE = re.compile(r"[^a-z0-9_]")


def _safe(s: str) -> str:
    return _SAFE_NAME_RE.sub("_", s.lower().strip())


def _company_slug(company: str) -> str:
    """Short safe slug for filenames — max 30 chars, no trailing underscores."""
    return _safe(company)[:30].rstrip("_")


# ── Main generator ───────────────────────────────────────────────────────────

def generate_wca_campaign(
    country: str,
    vertical: str,
    n_agents: int = 15,
    language: str = "es",
    sender_name: str = "Renato Alvarez",
    agents: list[dict] | None = None,
) -> bytes:
    """
    Return ZIP bytes containing:
      capability_deck.txt
      emails/email_001_CompanyName.txt … (personalised) or email_001.txt … (fallback)
      tracking_[country]_[vertical].csv

    Args:
        country:     Target country for the campaign.
        vertical:    Cargo vertical key (see _VERTICAL_ES).
        n_agents:    Number of anonymous agents when no agent list is provided
                     (fallback mode). Clamped to 10–30.
        language:    Email language: "es" | "en" | "de".
        sender_name: GT representative name for signatures.
        agents:      Optional list of dicts with keys "name", "company", "email".
                     When provided, generates one fully-personalised email per
                     agent with [AGENT_NAME] and [AGENT_COMPANY] replaced.
                     When None, falls back to n_agents anonymous templates.

    Raises:
        ValueError: If WCA_SENDER_EMAIL env var is not set.
    """
    sender_email = _get_sender_email()   # fail fast — no ZIP without confirmed address

    n_agents = max(10, min(30, int(n_agents)))
    lang     = language.lower()
    if lang not in _EMAIL_TMPLS:
        lang = "es"

    vertical_label = vertical.title()
    vertical_es    = _VERTICAL_ES.get(vertical.lower(), vertical)
    vertical_en    = _VERTICAL_EN.get(vertical.lower(), vertical)

    params = dict(
        country=country,
        vertical_label=vertical_label,
        vertical_es=vertical_es,
        vertical_en=vertical_en,
        sender_name=sender_name,
        sender_email=sender_email,
    )

    # Capability deck — one copy, same for all agents
    deck_text = _DECK_TMPL.safe_substitute(**params).encode("utf-8")

    email_tmpl = _EMAIL_TMPLS[lang]
    base_text  = email_tmpl.safe_substitute(**params)  # $vars resolved; [BRACKETS] remain

    # Tracking CSV
    csv_buf = io.StringIO()
    writer  = csv.writer(csv_buf)
    writer.writerow(TRACKING_COLUMNS)

    # Build ZIP in memory
    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("capability_deck.txt", deck_text)

        if agents:
            # ── Personalised mode ────────────────────────────────────────────
            for i, agent in enumerate(agents, 1):
                name    = agent.get("name",    f"[Agente {i:02d}]")
                company = agent.get("company", "[Empresa]")
                email   = agent.get("email",   "")

                personalised = (
                    base_text
                    .replace("[AGENT_NAME]",    name)
                    .replace("[AGENT_COMPANY]", company)
                )

                slug  = _company_slug(company)
                fname = f"emails/email_{i:03d}_{slug}.txt"
                zf.writestr(fname, personalised.encode("utf-8"))

                writer.writerow([name, company, email, "", "", ""])

        else:
            # ── Fallback mode: anonymous templates ───────────────────────────
            for i in range(1, n_agents + 1):
                fname = f"emails/email_{i:03d}.txt"
                zf.writestr(fname, base_text.encode("utf-8"))

                writer.writerow([
                    f"[Agente {i:02d}]", "[Empresa]", "[email@agente.com]", "", "", "",
                ])

        csv_name = f"tracking_{_safe(country)}_{_safe(vertical)}.csv"
        zf.writestr(csv_name, csv_buf.getvalue().encode("utf-8"))

    zip_buf.seek(0)
    return zip_buf.read()
